### ISSUE TITLE
undefined method `zscan' for #<MockRedis::Database:0xbde028c>

### ISSUE THREAD

**Issue by ArunSakthivel** [brigade/mock_redis#102]
Is it available ```zscan``` ?

Because, I'm getting below error, when I was run my rpsec

```
undefined method `zscan' for #<MockRedis::Database:0xbde028c>
```

**Comment by sds** [comment]
Hey @ArunSakthivel, 

`zscan` is not yet supported. Feel free to submit a pull request if you would like to see it added. :)
