### ISSUE TITLE
zrangebyscore doesn't work with exclusive ranges on both sides

### ISSUE THREAD

**Issue by nateyoder** [brigade/mock_redis#106]
@redises.zadd(@key, 1, 'Washington')
@redises.zadd(@key, 2, 'Adams')
@redises.zadd(@key, 3, 'Jefferson')
@redises.zadd(@key, 4, 'Madison')

it 'honors exclusive ranges on the left and the right simultaneously' do
  @redises.zrangebyscore(@key, '(1', '(4').should == ['Adams', 'Jefferson']
end

fails and returns with nothing

**Comment by sds** [comment]
Thanks for the report! 

Fixed in #107.
