### ISSUE TITLE
REDIS.dbsize errors when there is no data in MockRedis

### ISSUE THREAD

**Issue by dmitrypol** [brigade/mock_redis#122]
```
REDIS_APP_JOIN = Redis::Namespace.new(:appjoin, redis: MockRedis.new )
#
it 'invalid test' do
  # run the actual test
  expect(REDIS_APP_JOIN.dbsize).to eq 0
end
#
expected: 0
got: #<MockRedis::Future:0x00000001e8f660 @command=[:dbsize], @result_set=false>
```

The test is part of a gem I recently created https://github.com/dmitrypol/redis_app_join/blob/master/spec/redis_app_join_spec.rb#L37

Here is Gemfile.lock https://github.com/dmitrypol/redis_app_join/blob/master/Gemfile.lock

It works when there is data in Redis.  Has anyone experienced this?

**Comment by sds** [comment]
We have a test that explicitly checks the case where db size is zero: 

https://github.com/brigade/mock_redis/blob/68274651cfcfa7f5df9882160cdc1783a2688b44/spec/commands/dbsize_spec.rb#L7-L9

The fact that you're wrapping MockRedis with `Redis::Namespace` might be to blame here, though without an easily reproducible example (and the version of Redis server that you're using) it will be difficult to diagnose.

Would appreciate you digging into this further, as I personally won't have any time to look into this issue. Thanks!

**Comment by sds** [comment]
Closing due to lack of response. Feel free to reopen with a reproducible example. Thanks!
